ALTER TABLE real_estate_rent ADD COLUMN IF NOT EXISTS suburb VARCHAR(100);
ALTER TABLE real_estate_rent ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE real_estate_rent ADD COLUMN IF NOT EXISTS car_spaces INTEGER;
