import { pgTable, uuid, varchar, text, integer, decimal, timestamp, index, uniqueIndex } from 'drizzle-orm/pg-core';

export const appraisalLeads = pgTable('appraisal_leads', {
  id: uuid('id').primaryKey().defaultRandom(),
  client_name: varchar('client_name', { length: 100 }).notNull(),
  property_address: text('property_address').notNull(),
  email: varchar('email', { length: 150 }).notNull(),
  email_hash: varchar('email_hash', { length: 64 }).notNull(),
  phone: varchar('phone', { length: 50 }).notNull(),
  timeline: varchar('timeline', { length: 50 }),
  motivation: varchar('motivation', { length: 100 }),
  language_preference: varchar('language_preference', { length: 10 }),
  heard_from: varchar('heard_from', { length: 100 }),
  status: varchar('status', { length: 20 }).default('Pending'),
  agent_notes: text('agent_notes'),
  follow_up_at: timestamp('follow_up_at', { withTimezone: true }),
  source_page: varchar('source_page', { length: 100 }),
  utm_source: varchar('utm_source', { length: 100 }),
  utm_medium: varchar('utm_medium', { length: 100 }),
  utm_campaign: varchar('utm_campaign', { length: 100 }),
  suburb: varchar('suburb', { length: 100 }),
  property_type: varchar('property_type', { length: 50 }),
  priority: varchar('priority', { length: 20 }).default('medium'),
  contact_status: varchar('contact_status', { length: 50 }).default('not_contacted'),
  last_contact_at: timestamp('last_contact_at', { withTimezone: true }),
  region: varchar('region', { length: 100 }),
  city: varchar('city', { length: 100 }),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index('idx_appraisal_suburb').on(table.suburb),
  index('idx_appraisal_contact_status').on(table.contact_status),
  index('idx_appraisal_follow_up_at').on(table.follow_up_at),
  index('idx_appraisal_priority').on(table.priority),
  index('idx_appraisal_created_at').on(table.created_at),
  index('idx_appraisal_leads_region').on(table.region),
  index('idx_appraisal_leads_city').on(table.city),
]);

export const outreachSelectedProperties = pgTable('outreach_selected_properties', {
  id: uuid('id').primaryKey().defaultRandom(),
  louis_property_id: uuid('louis_property_id').notNull(),
  property_address: text('property_address').notNull(),
  suburb: varchar('suburb', { length: 100 }).notNull(),
  street: varchar('street', { length: 255 }),
  city: varchar('city', { length: 100 }),
  bedrooms: integer('bedrooms'),
  bathrooms: integer('bathrooms'),
  rv_value: decimal('rv_value', { precision: 10, scale: 2 }),
  status: varchar('status', { length: 20 }).default('PENDING'),
  selected_by: varchar('selected_by', { length: 255 }).notNull(),
  selected_at: timestamp('selected_at', { withTimezone: true }).defaultNow(),
  sent_by: varchar('sent_by', { length: 255 }),
  sent_at: timestamp('sent_at', { withTimezone: true }),
  tracking_code: varchar('tracking_code', { length: 50 }),
  notes: text('notes'),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('idx_outreach_status').on(table.status),
  index('idx_outreach_suburb').on(table.suburb),
  index('idx_outreach_selected_at').on(table.selected_at),
  uniqueIndex('idx_unique_property_user').on(table.louis_property_id, table.selected_by),
]);

export const reportDownloads = pgTable('report_downloads', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: varchar('email', { length: 255 }).notNull(),
  name: varchar('name', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  suburb: varchar('suburb', { length: 100 }).notNull(),
  report_type: varchar('report_type', { length: 50 }).default('local_market'),
  downloaded_at: timestamp('downloaded_at', { withTimezone: true }).defaultNow().notNull(),
  source: varchar('source', { length: 50 }),
  campaign_id: uuid('campaign_id'),
  tracking_code: varchar('tracking_code', { length: 50 }),
  user_agent: text('user_agent'),
  ip_address: varchar('ip_address', { length: 45 }),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index('idx_report_email_suburb').on(table.email, table.suburb),
  index('idx_report_downloaded_at').on(table.downloaded_at),
  index('idx_report_suburb').on(table.suburb),
  index('idx_report_tracking_code').on(table.tracking_code),
]);

export const suburbQrCodes = pgTable('suburb_qr_codes', {
  id: uuid('id').primaryKey().defaultRandom(),
  suburb: varchar('suburb', { length: 100 }).notNull(),
  target_url: varchar('target_url', { length: 500 }).notNull(),
  file_url: varchar('file_url', { length: 500 }).notNull(),
  file_name: varchar('file_name', { length: 200 }).notNull(),
  file_size: integer('file_size').default(0),
  uploaded_by: varchar('uploaded_by', { length: 255 }),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  uniqueIndex('idx_suburb_qr_codes_suburb').on(table.suburb),
]);

export const suburbReports = pgTable('suburb_reports', {
  id: uuid('id').primaryKey().defaultRandom(),
  suburb: varchar('suburb', { length: 100 }).notNull(),
  quarter: varchar('quarter', { length: 10 }).notNull(),
  year: integer('year').notNull(),
  file_url: text('file_url').notNull(),
  file_name: varchar('file_name', { length: 255 }).notNull(),
  file_size: integer('file_size'),
  download_count: integer('download_count').default(0),
  view_count: integer('view_count').default(0),
  status: varchar('status', { length: 20 }).default('active'),
  uploaded_by: varchar('uploaded_by', { length: 255 }),
  notes: text('notes'),
  uploaded_at: timestamp('uploaded_at', { withTimezone: true }).defaultNow().notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex('idx_suburb_reports_suburb_quarter').on(table.suburb, table.quarter, table.year),
  index('idx_suburb_reports_suburb').on(table.suburb),
  index('idx_suburb_reports_quarter').on(table.quarter, table.year),
  index('idx_suburb_reports_status').on(table.status),
  index('idx_suburb_reports_uploaded_at').on(table.uploaded_at),
]);
